washingtonstateuniversity/WSU-spine

styles/sass/_respond.scss
styles/sass/respond/_grid.scss

The prepares for the removal of deprecated "smallish" term for intermediate fixed layout

Intermediate controls

---

CHANGELOG.md
README.md
package.json

[PR] Bump versioning in develop branch

---

styles/sass/_respond.scss
styles/sass/respond/_states.scss

Adjust signature sizing and eliminate important declarations

---

scripts/ui.spine.framework.js

Enable optional equalizing for medium and small layouts

---

package.json

Filled via `npm-check-updates -u`, tested with grunt prod, dev, and build commands.

[PR] Update packages used with Grunt

---

styles/sass/_column.scss
styles/sass/spine/_colors.scss

Work on this is not complete and we're pending a new release of
the Spine. Moving to a feature branch to continue work.
This reverts commit f5ec35ae9f0d524104c99da324c4a83534e34564.

[PR] Revert "Add button backgrounds and animate menu icon"

---

CHANGELOG.md
styles/sass/_column.scss

[PR] Correct clipping of search text in Firefox, IE

---

spine.html
spine.min.html
test/preprocess/blocks/head.html
test/preprocess/test.cat.pre.html
test/preprocess/test.pre.html

[PR] Update recommended libraries jQuery 1.11.3 and jQuery 1.11.4

---

scripts/ui.spine.framework.js
scripts/ui.spine.search.js
styles/sass/_column.scss
styles/sass/_respond.scss
styles/sass/respond/_states.scss
styles/sass/skeleton/_headers.scss
styles/sass/vars/_global.scss

This is a follow-up to the still open #315 that implements things a slightly different way. All in progress.

[PR] Refactor portions of mobile menu handling

---

package.json
scripts/ui.spine.framework.js
styles/sass/_column.scss
styles/sass/_respond.scss
styles/sass/respond/_grid.scss
styles/sass/respond/_print.scss
styles/sass/respond/_states.scss
styles/sass/skeleton/_defaults.scss
styles/sass/skeleton/_forms.scss
styles/sass/skeleton/_headers.scss
styles/sass/skeleton/_layouts.scss
styles/sass/spine/_colors.scss
styles/sass/spine/_cropped.scss
styles/sass/vars/_global.scss
tasks/options/csslint.js

Going through some of the csslint stuff to clean up in areas where we can.

[PR] General improvements related to linting

---

scripts/ui.spine.framework.js

[PR] Rework logic and assignments in jacket sizing for clarity

---

styles/sass/vars/_global.scss

[PR] Add missing comma to fix broken rule for horizontal marks on mobile

---

styles/sass/_respond.scss
styles/sass/spine/_colors.scss

[PR] Bug mobile hover colors

---

scripts/ui.spine.framework.js

This uses similar logic to that used for the navigation items in the Spine.
Fixes #351.

[PR] Handle Spine action touches differently than clicks

---

styles/sass/_column.scss
styles/sass/skeleton/_boards.scss
styles/sass/skeleton/_headers.scss
styles/sass/spine/_colors.scss
styles/sass/vars/_colors.scss

See #353 for full discussion of changes.

[PR] Adjust Spine colors for various themes and nav elements

---

scripts/ui.spine.framework.js
test/preprocess/blocks/spine.html

[PR] Allow mixed HTML inside anchor tags in Spine Nav

---

scripts/ui.spine.framework.js

Reverts washingtonstateuniversity/WSU-spine#386

Revert "Allow the current section to be toggled open/closed"

---

scripts/ui.spine.framework.js

There were some deployment troubles yesterday after the merge of #386.

[PR] Revert #387 and restore #386

---

scripts/ui.spine.framework.js

[PR] Add a space before generated postal code HTML

---

spine.html
spine.min.html
test/preprocess/blocks/head.html

[PR] Update HTML5 shiv URL to new CDN location

---

test/preprocess/blocks/wp-admin-bar-head.html
test/preprocess/blocks/wp-admin-bar.html
test/preprocess/main.tmpl
test/sitemap.js

This will help troubleshoot issues in the Spine when viewing pages while logged in on the WSUWP platform.

[PR] Introduce Spine test layouts that include a fixed admin bar

---

.gitignore
package-lock.json

This thing confuses me to no end, but we seem to be better off with it than without it.

[PR] Use NPM's package-lock.json
