washingtonstateuniversity/WSU-spine

- CHANGELOG.md
- scripts/spine.js
- scripts/ui.spine.social.js
In the current state, `spineoptions` cannot be filled by an object on the outside. The check for an existing `spineoptions` will always result in an empty object.
This uses `window.spineoptions` to use any existing data that the document is trying to provide. Pages can now override defaults by creating their own `spineoptions` object in the global space.
Also added a warning about possible changes to option names. We'll need to make these more structured in the future so that they scale properly.
> [PR] Use the global `spineoptions` object when starting the Spine Framework

- styles/sass/_column.scss
There’s no need to require the li and li a to be nested in the ul in
terms of styling. This way, .spine-share can be on the container or on
the ul.
> Make spine share styling simpler.

- tasks/options/cssmin.js
This configuration is passed to css-clean by cssmin and prevents duplicate properties from being merged.
> [PR] Set advanced as false for cssmin to disable property merging

- scripts/ui.spine.framework.js
We're holding off on this until a future release as it should live
in a different area. See #268
This reverts commit 0690799b3d36c80612688392906935a2043863fa.
> [PR] Revert "Add click event to exposed search field"

- styles/sass/skeleton/_utilities.scss
By prefixing our background position utility classes with main, we can
use our utility classes in a class to class specificity battle while
only marginally increasing the specificity in the Spine framework.
> Remove trumps, use main to empower background positioning

- styles/sass/vars/_global.scss
I’m leaving the campaign signature style in there for now in the event that some sites
don’t get manually switched over immediately.
> Add foundation to signature style declarations

- scripts/ui.spine.framework.js
- scripts/ui.spine.js
- scripts/ui.spine.search.js
- scripts/ui.spine.social.js
I spent some time reading through the Spine JavaScript to familiarize myself so I could dig into a couple of our long standing bugs. This branch is a result of that process.
Updates:
* Add improved documentation throughout, adjust formatting in some areas.
* Only fire a passed callback once during mutation observation. Previously some actions would cause this to fire multiple times, which was unnecessary.
* Consolidate SVG support logic into one block.
There are a few things that may be nice to deprecate in the future unless they're in use somewhere else:
* `whenAll`
* The `debug.js` file
* `setup_jacket`
* `setup_binder`
* `setup_content`
There should be no real functional or visual change with this PR. The only slight modifications in behavior are SVG detection and `observeDOM`.
> [PR] Documentation refresh, review

- scripts/ui.spine.framework.js
Add the `#scroll` element to Android devices so that the navigation scrolls properly.
This may not be a long term solution, as some things are still quirky, but it gives users access to the content. We'll want to revisit the Spine behavior on mobile in general at some point in the future.
Fixes #235.
> [PR] Setup navigation scrolling for Android devices

- styles/sass/_column.scss
- styles/sass/_respond.scss
- styles/sass/respond/_print.scss
- styles/sass/skeleton/_asides.scss
- styles/sass/skeleton/_boards.scss
- styles/sass/skeleton/_defaults.scss
- styles/sass/skeleton/_forms.scss
- styles/sass/skeleton/_headers.scss
- styles/sass/skeleton/_shorthand.scss
- styles/sass/skeleton/_spineless.scss
- styles/sass/skeleton/_tables.scss
- styles/sass/skeleton/_unbind.scss
- styles/sass/skeleton/_utilities.scss
- styles/sass/spine/_cropped.scss
- tasks/options/csslint.js
This allows us to set the csslint rule for `zero-units` to `2`, which will stop Grunt with an error if any future 0 unit uses are found.
> [PR] Remove zero-units from CSS, adjust csslint to stop on error

- scripts/ui.spine.framework.js
`active` and `dogeared` are both important for proper styling in the navigation. This clarifies some of the logic attached to applying these styles and drops a `.active:not(:has(.active))` that was super confusing.
From what I can tell, everything appears to work as is and better in our test suite, which uses the `active` method and relies on the Spine to add `dogeared`.
> [PR] Simplify and document scripting to add `active`, `dogeared` to nav

- scripts/ui.spine.framework.js
- styles/sass/_column.scss
- styles/sass/respond/_states.scss
This provides for a sticky footer when the nav menu is sized differently for different views on mobile. This is already handled for non-mobile views.
> [PR] Position `#spine-footer` relatively when nav is longer than window on mobile

- scripts/ui.spine.framework.js
- styles/sass/_column.scss
- styles/sass/_respond.scss
- styles/sass/respond/_states.scss
On mobile page views, we need to position `.spine-footer` slightly below the edge of the window so that scrolling behavior acts as expected. We only need to handle this once, on the initial page view, as no menu collapsing happens after that. We can now remove the DOM change trigger for mobile views entirely.
> [PR] Additional work on mobile scrolling behavior

- scripts/ui.spine.js
- tasks/options/jshint.js
* Split JSHint options into two groups - one for Node/Grunt JS and another for the JavaScript powering the Spine.
* Remove deprecated rules that have been dropped from the JSHint library.
* Add rules to enforce some more strict development.
> [PR] Revisit and clarify JSHint options

- scripts/ui.spine.framework.js
We can avoid a small amount of processing by only triggering
actions that are necessary
> [PR] Only trigger and handle scroll events on non-mobile views

- styles/sass/_respond.scss
989px is the width at which we implement mobile navigation.
> [PR] Treat Spine mobile navigation the same in fluid, hybrid, and fixed

- scripts/ui.spine.framework.js
On page views where `main` was longer than the navigation, the
min height attached to the Spine action when an action was clicked
would be as high as main and create a confusing experience. This
change locks it to the height of the browser, similar to how the
Spine itself is handled.
Fixes #291
> [PR] Calculate Spine action tab heights on window height, not main

- scripts/ui.spine.framework.js
Previously, there were a couple hot spots that would cause glue to
jump prematurely to the top or bottom on scroll when unexpected.
This commit simplifies and reworks the logic a bit to better maintain
the state of `#glue` when the content is larger than the navigation.
* Set an upper bound for the `top` style attribute on `#spine`
* Watch for any positioning above 0 and reset to 0.
* Watch for any positioning outside the upper bound and reset to
the upper bound.
Fixes #266.
> [PR] Refactor how glue positioning is handled on scroll

- scripts/ui.spine.framework.js
- scripts/ui.spine.search.js
Not all browsers provide the same default for button types, so we should provide explicit defaults ourselves.
* The Spine menu button is a `button` type `button`.
* The Spine search tab submits a search form to search.wsu.edu if clicked and is a `submit` type `button`.
Closes #65.
> [PR] Provide explicit `button` types for buttons

- styles/sass/skeleton/_headers.scss
- tasks/options/csslint.js
This reverts f5098a473862cb. The `vertical-align` property will not apply to a block element, but there are sites using the Spine that have overridden the default `display` property to be `inline` or `inline-block` and now rely on this property being here as a fallback.
> [PR] Re-apply `vertical-align: baseline` to main header sup/sub

- package.json
- scripts/spine.js
- scripts/ui.spine.framework.js
- scripts/ui.spine.js
- scripts/ui.spine.search.js
- scripts/ui.spine.social.js
- scripts/wsu_autocomplete.js
- tasks/options/jscs.js
This provides the ability to do code sniffing with `grunt jscs`. We'll want to hook this up to the development grunt tasks and with continuous integration to help show status.
> [PR] Apply initial JSCS configuration to match jQuery code standards

- Gruntfile.js
- package.json
- tasks/options/copy.js
- tasks/options/env.js
* Remove `grunt-env` from the list of packages, it is unused.
* Remove `setbase` from `Gruntfile.js`, it is unused.
* Run `dev` as the `default` Grunt task.
* Add `jscs` task to the `dev` Grunt task.
* Consolidate task configuration in `Gruntfile.js`.
> [PR] Additional Gruntfile cleanup

- package.json
- tasks/build_tests.js
Wrench has been deprecated by its maintainer who suggests using
fs-extra instead.
https://www.npmjs.com/package/wrench
https://github.com/jprichardson/node-fs-extra
> [PR] Replace wrench with fs-extra

- styles/sass/_column.scss
> [PR] Only apply box shadow to `#glue` on `.spine-mobile-open`

- scripts/ui.spine.framework.js
Having this class applied caused the scroll to remain locked even
when the mobile nav was gone.
Fixes #369
> [PR] Remove `spine-mobile-open` from `html` on resize to full

- scripts/ui.spine.framework.js
When an overview list item is dynamically created, and its parent list item is marked as active, then add `opened` to the parent so that the open/close behavior can be used. Remove `active` as it is not necessary for functionality.
When a non-overview list item is marked as active, make sure its parent has the `opened` class so that it can be open/closed as well.
Fixes #368.
> Allow the current section to be toggled open/closed

- styles/sass/_column.scss
In previous versions of the Spine, users could not close an active
session so we removed the pointer cursor. This is no longer the case and
pointer should be the default cursor for all anchors.
Fixes #391.
> [PR] Remove cursor override for active parents

- styles/sass/skeleton/_forms.scss
The previous iteration had a contrast of 4.48 to 1, slightly below the WCAG 2.0 AA limit. This adjusts to a 4.54 to 1 contrast ratio.
> [PR] Fix contrast issue for non-focused text inputs

- scripts/ui.spine.framework.js
This is used when calculating the height of the spine and glue elements to account for a case when a CMS (WordPress) has a fixed bar at the top of the screen.
Setting `spineoptions.framework.viewport_offset` to `32` in that instance will allow the Spine to be resized accordingly.
> [PR] Introduce a viewport_offset option to the Spine

- scripts/ui.spine.framework.js
In cases where a fixed bar is displayed at the top of the page (WordPress), the Spine wasn't able to calculate its proper position.
> [PR] Account for the viewport offset when calculating the upper bound

- scripts/ui.spine.framework.js
The selector attached to this was a bit too general, causing the menu to toggle in unexpected (though admittedly outlier) cases.
> [PR] Increase the specificity of the mobile menu toggle method

- styles/jqueryui.css
- styles/sass/skeleton/_forms.scss
When borders and backgrounds are added to input fields, Firefox apparently stops showing the default focus styles.
> Adjust input styles to better support Firefox focus
